### ISSUE TITLE
Idle View background cover doesn't span full about page height

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#123]
critical for V1: currently the background cover doesn't fill the full height of the about page:

![Screen Shot 2022-05-28 at 13 06 57](https://user-images.githubusercontent.com/902958/170822896-2f304eab-46ab-44e7-9398-420757e4fcb2.png)

**Comment by phivk** [comment]
critical for V1: currently the background cover doesn't fill the full height of the about page:

![Screen Shot 2022-05-28 at 13 06 57](https://user-images.githubusercontent.com/902958/170822896-2f304eab-46ab-44e7-9398-420757e4fcb2.png)

**Comment by Solcany** [comment]
done in #159
