### ISSUE TITLE
ensure all views can be navigated on mobile screen sizes

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#132]
currently some views have their controls and texts inaccessible on smaller mobile screens:
![Screenshot_2022-05-23-10-21-34-434_org mozilla firefox](https://user-images.githubusercontent.com/902958/169776320-5760c6bb-e1f8-4369-ac58-e6c7b31a9b23.jpg)

**Comment by Solcany** [comment]
implemented in #196

**Comment by phivk** [comment]
Reopening as PR is still work in progress
