### ISSUE TITLE
small layout and style issues

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#138]
- [x] make form less serious
- [x] reduce ch3 other head icon size
- [x] increase informed consest paragraph text
- [x] increase Chapter Opening paragraph texts
- [x] make submit button smaller and less intimidating
- [x] make Skip button less prominent
- [x] Animate loading of pages
- [x] compress all images
- [x] increase line height in the basic text
- [x] emphasize read more button 
- [x] add read more link to the end of the experience
- ~[ ] confirm exit app modal~ already has separate issue: https://github.com/phivk/tolerant-futures/issues/88
- [x] add z-index to ui elements overlapped with the circle shadow in game comp
- [x] style read more link

**Comment by phivk** [comment]
added: reduce ch3 other head icon size

**Comment by Solcany** [comment]
added: add z-index to ui elements overlapped with the circle shadow in game comp

**Comment by Solcany** [comment]
done in #159
