### ISSUE TITLE
improve styling of TheExitConfirmation component

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#158]
currently it looks like this:
 
Ideally the ButtonSecondary would be less pronounced (e.g. by removing the contrasting bg color)

Work on this issue could go hand in hand with Styling TheIdleView https://github.com/phivk/tolerant-futures/issues/148

![Screen Shot 2022-05-29 at 18 54 01](https://user-images.githubusercontent.com/902958/170882103-0a01a03e-5fbc-41a1-914d-d031fa72a416.png)

**Comment by Solcany** [comment]
done in #159
