### ISSUE TITLE
Styling: On safari spectra edges are cut off

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#172]
Both on Safari on Mac (regular and responsive mode set to iPad) and on iPad
<img width="1792" alt="Screenshot 2022-06-01 at 15 23 59" src="https://user-images.githubusercontent.com/902958/171416314-221f79a4-84b0-4e1e-a63a-faee37891e13.png">

**Comment by Solcany** [comment]
fixed in #195
