### ISSUE TITLE
Hide subtitles when feedback modal is rendered

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#43]
![Screenshot 2022-05-01 at 16 18 26](https://user-images.githubusercontent.com/18234033/166150055-f859fa97-2c8c-4129-95fd-908c840525b7.png)

**Comment by phivk** [comment]
fixed via https://github.com/phivk/tolerant-futures/pull/38/commits/062ed702bd08c501f9e0ccdbbc11fd85dcf5f4ca

**Comment by phivk** [comment]
fixed via https://github.com/phivk/tolerant-futures/pull/38/commits/062ed702bd08c501f9e0ccdbbc11fd85dcf5f4ca
