### ISSUE TITLE
Fix card text overflow

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#45]
![Screenshot 2022-05-01 at 16 24 01](https://user-images.githubusercontent.com/18234033/166150254-3b87aeff-087b-464e-bd35-eb6d81c387eb.png)

**Comment by phivk** [comment]
two things to fix about the current design:

- [ ] CardItem text overflows the inner border
- [X] SubtitlePlayer spans entire width. I think it would be more legible if it has a max width conducive for reading, similar to Tachyons’ [measure](https://tachyons.io/docs/typography/measure/) style
