### ISSUE TITLE
Dynamically generate player feedback prompt using the spectrum and the concept(s)

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#47]
![Screenshot 2022-05-01 at 16 26 19](https://user-images.githubusercontent.com/18234033/166150427-6937d072-525e-427e-b14d-8ef3f2ca00ef.png)

**Comment by phivk** [comment]
closed via https://github.com/phivk/tolerant-futures/pull/38/commits/062ed702bd08c501f9e0ccdbbc11fd85dcf5f4ca
