### ISSUE TITLE
future prompt should have it's own visual identity

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#55]
currently using ChapterOpening component as placeholder:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/902958/166161831-2bab0bfa-f8da-4915-b904-35299f60e46f.png">

Ideally, it should:

- visually distinct from the ChapterOpenings
- encourage people to read the full text
- encourage people to not click away too quickly
- encourage people to feel they have achieved something great

**Comment by Solcany** [comment]
implemented in #142
