### ISSUE TITLE
Ch3: Subtitles react to the player's plays after the true position of the other's card has been revealed

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#72]
![Screenshot 2022-05-05 at 22 03 21](https://user-images.githubusercontent.com/18234033/167016797-b709231e-a112-42e7-ab6b-1d6e4ed3df2c.png)

**Comment by phivk** [comment]
What do you mean by reacting?
Isn't the issue that the cards can still be dragged? If we disabled dragging after confirming, this should be fixed, right?

**Comment by Solcany** [comment]
Yeah that'll fix it

**Comment by phivk** [comment]
This had been fixed by disabling dragging of cards after confirming their value
