### ISSUE TITLE
fix the ChapterOpeningOtherPlayer architecture

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#80]
![Screenshot 2022-05-07 at 12 32 31](https://user-images.githubusercontent.com/18234033/167250590-0d8721c3-e961-4b1b-b8e8-a0ff07f16c6e.png)

**Comment by phivk** [comment]
fixed via https://github.com/phivk/tolerant-futures/pull/147/commits/b2a8c102f59b24b0d9d7245297841719273bab76
