### ISSUE TITLE
store past concept hints in Supabase and retrieve them in SpectrumGame

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#83]
This is related to #82 . We need to write hints explaning each past concept. They need to be retrieved from the supabase and rendered in SpectrumGame (rendering is already implemented in #82 )

**Comment by phivk** [comment]
@Solcany there is no need to store these things in SupaBase. They can more easily be fetched from [the local json file](https://github.com/phivk/tolerant-futures/blob/main/data/concepts.json) as is already happening.

Is there anything else that we need as part of this issue? If not, feel free to close :)
