### ISSUE TITLE
ch3: improve layout and styling of two parallel feedback forms

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#89]
I added minimal viable styling to ModalTextRevealer and SpectrumGameSelfOther.
Would be good to increase readability and make it more consistent with the rest of the app.

current minimal viable version:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/902958/167498111-7a6ba5db-f28b-4537-9e44-91aec5e863e7.png">

Critical for v2:

- improve readability of input text, when blur is not available (e.g. Firefox) 
- hidden text should be really hidden, when blur is not available (e.g. Firefox)

**Comment by phivk** [comment]
BTW I positioned them vertically because I thought we'd keep Self near bottom and Other near top. 
What are your thoughts on that?

**Comment by Solcany** [comment]
done in #159
