### ISSUE TITLE
fetch gradient class from local spectra data

### ISSUE THREAD

**Issue by phivk** [phivk/tolerant-futures#99]
add gradient classes to https://github.com/phivk/tolerant-futures/blob/main/data/spectra.json
as discussed on slack: https://tolerantfutures.slack.com/archives/C032606TLK1/p1651764741605299?thread_ts=1651762502.759049&cid=C032606TLK1

TODO:

- [x] add gradientClass to spectra data
- [x] refactor spectrum getter function
- [x] load gradientClass in turn data
- [x] pass gradientClass from data to DropZoneBackground
- [x] generate all 19 gradient styles in gradients.scss
- [x] number gradientClasses in spectra.json from 1 - 19

**Comment by phivk** [comment]
@Solcany I've left two last TODOs for you :)

**Comment by phivk** [comment]
see this draft PR: https://github.com/phivk/tolerant-futures/pull/100

**Comment by phivk** [comment]
@Solcany can this issue be closed?

**Comment by Solcany** [comment]
gradient color data added in #127
